# Generated by Django 4.0.4 on 2022-05-01 18:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cipherhistory',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='keygenhistory',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
