# Generated by Django 4.0.4 on 2022-05-02 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_cipherhistory_result_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cipherhistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='keygenhistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
